spring.application.name=votingapp

# DATABASE CONFIG
spring.datasource.url=jdbc:mysql://localhost:3306/votingapp
spring.datasource.username=root
spring.datasource.password=Abhi@1101
spring.jpa.hibernate.ddl-auto=update
springdoc.swagger-ui.customCssUrl=/swagger-dark.css
springdoc.swagger-ui.customCss=/swagger-dark.css